# [ 5-3. 운영사업비 모델링 ]

In [3]:
import pandas as pd
from pandas import DataFrame, Series
import cafle
from cafle import Index, Account
from cafle import Setattr

In [4]:
from practice.astn0_overview import overview, idx
from practice.astn1_sales import sales

## 1. Cost Account 설정

In [5]:
cost = Account(idx)

### 1) 토지비 가정

In [6]:
cost.토지비 = cost.subacc('토지비')
with cost.토지비 as 토지비:
    토지비.토지매입가액 = 토지비.subacc('토지매입가액')
    with 토지비.토지매입가액 as c:
        c.대지면적 = overview['area']['대지면적']['평']
        c.평단가 = 45 #백만원/평
        c.amt = c.대지면적 * c.평단가
        c.addscd(idx.loan[0], c.amt)

    토지비.취득세 = 토지비.subacc('취득세')
    with 토지비.취득세 as c:
        c.취득세율 = 0.046
        c.과세표준 = 토지비.토지매입가액.amt
        c.amt = round(c.과세표준 * c.취득세율)
        c.addscd(idx.loan[0], c.amt)
        
    토지비.중개수수료 = 토지비.subacc('중개수수료')
    with 토지비.중개수수료 as c:
        c.수수료율 = 0.01
        c.취득가액 = 토지비.토지매입가액.amt
        c.amt = round(c.취득가액 * c.수수료율)
        c.addscd(idx.loan[0], c.amt)
        
    토지비.부수비용 = 토지비.subacc('부수비용')
    with 토지비.부수비용 as c:
        c.적용비율 = 0.003
        c.취득가액 = 토지비.토지매입가액.amt
        c.amt = round(c.취득가액 * c.적용비율)
        c.addscd(idx.loan[0], c.amt)
        
    토지비.amtlst = Series(
        {key: val.amt for key, val in 토지비.dct.items()}
    )
    토지비.amt = 토지비.amtlst.sum()
    
    토지비.smry = {
        key: {
            subkey: getattr(subacc, subkey) for subkey in
                [var for var in subacc.vars if var not in ['index', 'name']]
        }
        for key, subacc in 토지비.dct.items()
    }

In [7]:
cost.토지비

Account(토지비, len 30, dct: ['토지매입가액', '취득세', '중개수수료', '부수비용'])

In [8]:
cost.토지비.토지매입가액.amt

20430

In [9]:
cost.토지비.토지매입가액.dfall

             scd_in  scd_in_cum  scd_out  scd_out_cum  bal_strt  amt_in  amt_in_cum  amt_out  amt_out_cum  bal_end  rsdl_in_cum  rsdl_out_cum
2023-01-31      0.0         0.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0          0.0           0.0
2023-02-28      0.0         0.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0          0.0           0.0
2023-03-31  20430.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-04-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-05-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-06-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-07-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-08-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-09-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-10-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-11-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2023-12-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-01-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-02-29      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-03-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-04-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-05-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-06-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-07-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-08-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-09-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-10-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-11-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2024-12-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2025-01-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2025-02-28      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2025-03-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2025-04-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2025-05-31      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0
2025-06-30      0.0     20430.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      20430.0           0.0

In [10]:
cost.토지비.amt

21635

In [11]:
cost.토지비.amtlst

토지매입가액    20430
취득세         940
중개수수료       204
부수비용         61
dtype: int64

In [12]:
cost.토지비.smry

{'토지매입가액': {'대지면적': 454, '평단가': 45, 'amt': 20430},
 '취득세': {'취득세율': 0.046, '과세표준': 20430, 'amt': 940},
 '중개수수료': {'수수료율': 0.01, '취득가액': 20430, 'amt': 204},
 '부수비용': {'적용비율': 0.003, '취득가액': 20430, 'amt': 61}}

### 2) Cost setting 함수 만들기

In [13]:
def costsetting(cst):
    cst.amtlst = Series(
        {key: val.amt for key, val in cst.dct.items()}
    )
    cst.amt = cst.amtlst.sum()
    cst.smry = {
        key: {
            subkey: getattr(subacc, subkey) for subkey in
                [var for var in subacc.vars if var not in ['index', 'name']]
        }
        for key, subacc in cst.dct.items()
    }

In [14]:
cost.토지비 = cost.subacc('토지비')
with cost.토지비 as 토지비:
    토지비.토지매입가액 = 토지비.subacc('토지매입가액')
    with 토지비.토지매입가액 as c:
        c.대지면적 = overview['area']['대지면적']['평']
        c.평단가 = 45#백만원/평
        c.amt = c.대지면적 * c.평단가
        c.addscd(idx.loan[0], c.amt)

    토지비.취득세 = 토지비.subacc('취득세')
    with 토지비.취득세 as c:
        c.취득세율 = 0.046
        c.과세표준 = 토지비.토지매입가액.amt
        c.amt = round(c.과세표준 * c.취득세율)
        c.addscd(idx.loan[0], c.amt)
        
    토지비.중개수수료 = 토지비.subacc('중개수수료')
    with 토지비.중개수수료 as c:
        c.수수료율 = 0.01
        c.취득가액 = 토지비.토지매입가액.amt
        c.amt = round(c.취득가액 * c.수수료율)
        c.addscd(idx.loan[0], c.amt)
        
    토지비.부수비용 = 토지비.subacc('부수비용')
    with 토지비.부수비용 as c:
        c.적용비율 = 0.003
        c.취득가액 = 토지비.토지매입가액.amt
        c.amt = round(c.취득가액 * c.적용비율)
        c.addscd(idx.loan[0], c.amt)
        
    costsetting(토지비)

In [15]:
cost.토지비.amtlst

토지매입가액    20430
취득세         940
중개수수료       204
부수비용         61
dtype: int64

In [16]:
cost.토지비.smry

{'토지매입가액': {'대지면적': 454, '평단가': 45, 'amt': 20430},
 '취득세': {'취득세율': 0.046, '과세표준': 20430, 'amt': 940},
 '중개수수료': {'수수료율': 0.01, '취득가액': 20430, 'amt': 204},
 '부수비용': {'적용비율': 0.003, '취득가액': 20430, 'amt': 61}}

In [17]:
cost.토지비.amt

21635

### 3) 공사비 가정

#### (1) 철거비 설정

In [18]:
cost.공사비 = cost.subacc('공사비')
with cost.공사비 as 공사비:
    공사비.철거비 = 공사비.subacc('철거비')
    with 공사비.철거비 as c:
        c.기존건물면적 = 700#평
        c.철거단가 = 0.3#백만원/평
        c.amt = c.기존건물면적 * c.철거단가
        c.addscd(idx.cstrn[0], c.amt)

#### (2) 표준공정률에서 본건 공정률 추출

In [20]:
stdprc = pd.read_excel('data/standard_process_rate.xlsx') # "openpyxl"을 설치해야 할 수 있음 "pip install openpyxl"
stdprc

     M    1      2      3      4      5      6      7      8      9     10     11     12     13     14     15     16     17     18     19     20     21     22     23     24     25     26     27     28     29     30     31     32     33     34     35     36     37     38     39     40     41     42     43     44     45     46     47     48
0    1  1.0  0.287  0.160  0.096  0.069  0.057  0.050  0.044  0.039  0.034  0.029  0.026  0.022  0.020  0.017  0.015  0.014  0.013  0.012  0.011  0.011  0.011  0.011  0.011  0.011  0.011  0.011  0.012  0.012  0.012  0.013  0.013  0.014  0.013  0.011  0.010  0.008  0.007  0.007  0.004  0.004  0.004  0.004  0.004  0.004  0.004  0.004  0.004
1    2  NaN  0.713  0.374  0.191  0.140  0.103  0.072  0.052  0.041  0.035  0.033  0.031  0.031  0.030  0.030  0.029  0.027  0.026  0.024  0.023  0.021  0.018  0.016  0.015  0.013  0.011  0.010  0.008  0.006  0.005  0.003  0.002  0.001  0.001  0.002  0.003  0.004  0.005  0.005  0.007  0.007  0.007  0.007  0.007  0.007  0.007  0.007  0.007
2    3  NaN    NaN  0.466  0.404  0.206  0.127  0.108  0.095  0.080  0.064  0.050  0.039  0.031  0.026  0.022  0.020  0.019  0.018  0.019  0.018  0.018  0.019  0.019  0.018  0.018  0.019  0.018  0.017  0.017  0.017  0.016  0.016  0.014  0.014  0.014  0.013  0.012  0.011  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.008  0.008  0.008
3    4  NaN    NaN    NaN  0.309  0.363  0.247  0.141  0.096  0.081  0.076  0.071  0.064  0.055  0.046  0.039  0.032  0.027  0.023  0.019  0.017  0.015  0.014  0.014  0.013  0.013  0.012  0.013  0.013  0.014  0.013  0.014  0.013  0.014  0.013  0.013  0.013  0.014  0.013  0.013  0.013  0.013  0.013  0.013  0.013  0.013  0.010  0.010  0.010
4    5  NaN    NaN    NaN    NaN  0.222  0.298  0.254  0.171  0.109  0.078  0.065  0.061  0.059  0.056  0.052  0.047  0.041  0.036  0.031  0.027  0.024  0.020  0.017  0.016  0.014  0.013  0.011  0.011  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010  0.010
5    6  NaN    NaN    NaN    NaN    NaN  0.168  0.243  0.233  0.184  0.128  0.089  0.066  0.056  0.052  0.049  0.048  0.047  0.044  0.041  0.037  0.033  0.030  0.027  0.023  0.021  0.018  0.017  0.015  0.013  0.012  0.011  0.010  0.009  0.009  0.009  0.008  0.008  0.009  0.008  0.008  0.008  0.008  0.008  0.008  0.008  0.008  0.008  0.008
6    7  NaN    NaN    NaN    NaN    NaN    NaN  0.132  0.203  0.206  0.183  0.141  0.102  0.074  0.057  0.049  0.045  0.043  0.041  0.040  0.040  0.038  0.035  0.032  0.030  0.028  0.026  0.022  0.020  0.019  0.017  0.015  0.014  0.013  0.012  0.010  0.010  0.009  0.008  0.008  0.008  0.008  0.008  0.008  0.008  0.008  0.008  0.008  0.008
7    8  NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.106  0.173  0.180  0.172  0.145  0.113  0.084  0.064  0.051  0.043  0.040  0.038  0.036  0.036  0.036  0.035  0.034  0.031  0.029  0.028  0.026  0.023  0.022  0.020  0.018  0.016  0.015  0.014  0.013  0.012  0.011  0.010  0.009  0.009  0.009  0.009  0.009  0.009  0.009  0.009  0.009
8    9  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.087  0.149  0.158  0.157  0.142  0.119  0.093  0.072  0.056  0.046  0.040  0.036  0.034  0.033  0.032  0.031  0.031  0.031  0.030  0.028  0.027  0.025  0.023  0.022  0.021  0.019  0.018  0.016  0.015  0.014  0.013  0.012  0.012  0.012  0.012  0.012  0.012  0.012  0.012  0.012
9   10  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.073  0.131  0.141  0.143  0.135  0.119  0.099  0.080  0.063  0.050  0.042  0.036  0.032  0.031  0.030  0.029  0.028  0.028  0.028  0.028  0.027  0.026  0.025  0.023  0.022  0.021  0.020  0.018  0.017  0.016  0.015  0.015  0.015  0.015  0.015  0.015  0.015  0.015  0.015
10  11  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.061  0.115  0.125  0.129  0.127  0.116  0.101  0.084  0.068  0.055  0.045  0.039  0.033  0.030  0.029  0.028  0.027  0.026  0.026  0.025  0.025  0.025  0.025  0.024  0.022  0.021  0.021  0.020  0.019  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018
11  12  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.053  0.104  0.114  0.117  0.117  0.111  0.100  0.087  0.073  0.060  0.050  0.042  0.036  0.031  0.028  0.026  0.026  0.024  0.024  0.024  0.023  0.023  0.023  0.023  0.023  0.021  0.021  0.020  0.019  0.019  0.019  0.019  0.019  0.019  0.019  0.018  0.018
12  13  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.045  0.092  0.104  0.108  0.109  0.106  0.099  0.088  0.076  0.064  0.054  0.045  0.038  0.033  0.029  0.026  0.025  0.024  0.023  0.023  0.022  0.022  0.022  0.021  0.022  0.020  0.021  0.020  0.020  0.020  0.019  0.019  0.019  0.019  0.018  0.018
13  14  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.040  0.083  0.095  0.098  0.100  0.099  0.095  0.087  0.077  0.067  0.057  0.048  0.041  0.035  0.031  0.027  0.025  0.023  0.022  0.021  0.021  0.020  0.020  0.020  0.020  0.019  0.020  0.020  0.020  0.020  0.020  0.020  0.020  0.019  0.019
14  15  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.035  0.075  0.088  0.092  0.093  0.093  0.091  0.085  0.077  0.069  0.060  0.051  0.045  0.038  0.033  0.029  0.026  0.024  0.022  0.021  0.021  0.020  0.019  0.020  0.019  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018
15  16  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.031  0.068  0.081  0.085  0.087  0.088  0.087  0.083  0.076  0.070  0.062  0.053  0.046  0.041  0.035  0.031  0.027  0.025  0.022  0.020  0.020  0.019  0.018  0.019  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018
16  17  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.028  0.062  0.076  0.079  0.081  0.082  0.081  0.080  0.075  0.069  0.063  0.056  0.048  0.043  0.037  0.032  0.029  0.026  0.024  0.021  0.020  0.019  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018
17  18  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.025  0.057  0.070  0.074  0.076  0.078  0.077  0.076  0.073  0.068  0.063  0.057  0.050  0.045  0.040  0.035  0.030  0.027  0.025  0.022  0.021  0.019  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018  0.018
18  19  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.022  0.053  0.065  0.069  0.071  0.073  0.073  0.073  0.071  0.067  0.063  0.058  0.052  0.046  0.041  0.037  0.032  0.029  0.026  0.023  0.021  0.020  0.020  0.020  0.020  0.020  0.020  0.018  0.018  0.018
19  20  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.020  0.048  0.062  0.066  0.068  0.069  0.070  0.069  0.068  0.065  0.061  0.057  0.053  0.047  0.043  0.038  0.034  0.030  0.027  0.024  0.022  0.022  0.022  0.022  0.022  0.022  0.022  0.022  0.022
20  21  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.019  0.044  0.057  0.062  0.064  0.065  0.066  0.066  0.066  0.064  0.061  0.057  0.053  0.048  0.044  0.039  0.036  0.032  0.029  0.025  0.025  0.025  0.024  0.024  0.024  0.024  0.024  0.024
21  22  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.017  0.041  0.053  0.059  0.060  0.062  0.063  0.063  0.063  0.061  0.059  0.056  0.053  0.049  0.045  0.041  0.036  0.033  0.030  0.030  0.030  0.030  0.030  0.030  0.030  0.030  0.030
22  23  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.016  0.039  0.050  0.056  0.058  0.059  0.060  0.060  0.061  0.060  0.058  0.055  0.052  0.049  0.045  0.042  0.038  0.035  0.035  0.032  0.032  0.032  0.032  0.032  0.032  0.032
23  24  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.014  0.036  0.048  0.053  0.055  0.056  0.057  0.057  0.057  0.058  0.056  0.055  0.051  0.049  0.045  0.042  0.038  0.038  0.035  0.035  0.035  0.035  0.035  0.035  0.035
24  25  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.013  0.033  0.045  0.050  0.052  0.054  0.055  0.055  0.055  0.055  0.054  0.053  0.051  0.049  0.046  0.043  0.043  0.039  0.039  0.039  0.039  0.039  0.039  0.039
25  26  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.012  0.030  0.042  0.048  0.050  0.051  0.053  0.053  0.054  0.053  0.053  0.051  0.050  0.047  0.045  0.045  0.040  0.040  0.040  0.040  0.040  0.040  0.040
26  27  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.012  0.029  0.040  0.045  0.048  0.049  0.050  0.050  0.051  0.051  0.051  0.050  0.049  0.047  0.047  0.042  0.041  0.041  0.041  0.041  0.041  0.041
27  28  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.011  0.027  0.038  0.043  0.046  0.047  0.048  0.049  0.049  0.050  0.049  0.049  0.048  0.048  0.045  0.045  0.045  0.045  0.045  0.045  0.041
28  29  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.010  0.025  0.036  0.041  0.044  0.046  0.046  0.047  0.047  0.048  0.048  0.047  0.047  0.046  0.046  0.046  0.046  0.045  0.045  0.041
29  30  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.010  0.024  0.034  0.040  0.042  0.044  0.045  0.045  0.045  0.046  0.046  0.046  0.047  0.047  0.047  0.045  0.045  0.045  0.043
30  31  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.009  0.022  0.032  0.038  0.041  0.042  0.043  0.044  0.044  0.045  0.045  0.045  0.045  0.045  0.042  0.042  0.042  0.042
31  32  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.009  0.021  0.030  0.036  0.039  0.040  0.041  0.041  0.042  0.042  0.041  0.041  0.041  0.037  0.037  0.037  0.037
32  33  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.008  0.020  0.029  0.034  0.038  0.039  0.040  0.041  0.041  0.040  0.040  0.040  0.035  0.035  0.035  0.035
33  34  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.008  0.019  0.028  0.033  0.037  0.038  0.038  0.038  0.037  0.037  0.037  0.034  0.034  0.034  0.034
34  35  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.007  0.018  0.026  0.031  0.035  0.037  0.036  0.035  0.035  0.035  0.033  0.031  0.031  0.031
35  36  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.007  0.017  0.026  0.031  0.033  0.033  0.033  0.033  0.033  0.030  0.030  0.030  0.030
36  37  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.007  0.016  0.024  0.030  0.028  0.030  0.030  0.030  0.027  0.027  0.027  0.027
37  38  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.006  0.015  0.023  0.022  0.025  0.025  0.025  0.025  0.025  0.025  0.025
38  39  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.006  0.014  0.013  0.022  0.022  0.016  0.025  0.025  0.025  0.025
39  40  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.006  0.006  0.013  0.012  0.010  0.016  0.014  0.014  0.014
40  41  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.005  0.006  0.006  0.008  0.010  0.012  0.012  0.012
41  42  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.005  0.005  0.006  0.008  0.010  0.010  0.010
42  43  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.004  0.005  0.006  0.008  0.008  0.010
43  44  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.004  0.005  0.006  0.006  0.008
44  45  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.004  0.005  0.005  0.006
45  46  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.004  0.004  0.005
46  47  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.003  0.004
47  48  NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  0.003

In [21]:
lencstrn = len(idx.cstrn)
cstrnprc = stdprc[lencstrn][:lencstrn]
cstrnprc.index = idx.cstrn
cstrnprc._name = '공정률'
cstrnprc

2023-04-30    0.011
2023-05-31    0.015
2023-06-30    0.018
2023-07-31    0.013
2023-08-31    0.016
2023-09-30    0.023
2023-10-31    0.030
2023-11-30    0.034
2023-12-31    0.031
2024-01-31    0.030
2024-02-29    0.030
2024-03-31    0.036
2024-04-30    0.045
2024-05-31    0.057
2024-06-30    0.069
2024-07-31    0.076
2024-08-31    0.080
2024-09-30    0.077
2024-10-31    0.073
2024-11-30    0.068
2024-12-31    0.062
2025-01-31    0.053
2025-02-28    0.039
2025-03-31    0.014
Name: 공정률, dtype: float64

#### (3) 건축비 설정

In [22]:
with cost.공사비 as 공사비:    
    공사비.건축비 = 공사비.subacc('건축비')
    with 공사비.건축비 as c:
        c.공사단가 = 5.50#백만원
        c.연면적 = overview['area']['연면적']['평']
        c.amt = c.공사단가 * c.연면적
        c.공정률표 = DataFrame(cstrnprc)
        c.공정률표['공정금액'] = c.공정률표['공정률'] * c.amt
        c.addscd(idx.cstrn, c.공정률표['공정금액'])

In [23]:
cost.공사비.건축비.공정률표

              공정률       공정금액
2023-04-30  0.011   237.9465
2023-05-31  0.015   324.4725
2023-06-30  0.018   389.3670
2023-07-31  0.013   281.2095
2023-08-31  0.016   346.1040
2023-09-30  0.023   497.5245
2023-10-31  0.030   648.9450
2023-11-30  0.034   735.4710
2023-12-31  0.031   670.5765
2024-01-31  0.030   648.9450
2024-02-29  0.030   648.9450
2024-03-31  0.036   778.7340
2024-04-30  0.045   973.4175
2024-05-31  0.057  1232.9955
2024-06-30  0.069  1492.5735
2024-07-31  0.076  1643.9940
2024-08-31  0.080  1730.5200
2024-09-30  0.077  1665.6255
2024-10-31  0.073  1579.0995
2024-11-30  0.068  1470.9420
2024-12-31  0.062  1341.1530
2025-01-31  0.053  1146.4695
2025-02-28  0.039   843.6285
2025-03-31  0.014   302.8410

In [24]:
cost.공사비.건축비.dfall

               scd_in  scd_in_cum  scd_out  scd_out_cum  bal_strt  amt_in  amt_in_cum  amt_out  amt_out_cum  bal_end  rsdl_in_cum  rsdl_out_cum
2023-01-31     0.0000      0.0000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       0.0000           0.0
2023-02-28     0.0000      0.0000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       0.0000           0.0
2023-03-31     0.0000      0.0000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       0.0000           0.0
2023-04-30   237.9465    237.9465      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0     237.9465           0.0
2023-05-31   324.4725    562.4190      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0     562.4190           0.0
2023-06-30   389.3670    951.7860      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0     951.7860           0.0
2023-07-31   281.2095   1232.9955      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    1232.9955           0.0
2023-08-31   346.1040   1579.0995      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    1579.0995           0.0
2023-09-30   497.5245   2076.6240      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    2076.6240           0.0
2023-10-31   648.9450   2725.5690      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    2725.5690           0.0
2023-11-30   735.4710   3461.0400      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    3461.0400           0.0
2023-12-31   670.5765   4131.6165      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    4131.6165           0.0
2024-01-31   648.9450   4780.5615      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    4780.5615           0.0
2024-02-29   648.9450   5429.5065      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    5429.5065           0.0
2024-03-31   778.7340   6208.2405      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    6208.2405           0.0
2024-04-30   973.4175   7181.6580      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    7181.6580           0.0
2024-05-31  1232.9955   8414.6535      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    8414.6535           0.0
2024-06-30  1492.5735   9907.2270      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0    9907.2270           0.0
2024-07-31  1643.9940  11551.2210      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   11551.2210           0.0
2024-08-31  1730.5200  13281.7410      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   13281.7410           0.0
2024-09-30  1665.6255  14947.3665      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   14947.3665           0.0
2024-10-31  1579.0995  16526.4660      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   16526.4660           0.0
2024-11-30  1470.9420  17997.4080      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   17997.4080           0.0
2024-12-31  1341.1530  19338.5610      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   19338.5610           0.0
2025-01-31  1146.4695  20485.0305      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   20485.0305           0.0
2025-02-28   843.6285  21328.6590      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   21328.6590           0.0
2025-03-31   302.8410  21631.5000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   21631.5000           0.0
2025-04-30     0.0000  21631.5000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   21631.5000           0.0
2025-05-31     0.0000  21631.5000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   21631.5000           0.0
2025-06-30     0.0000  21631.5000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0   21631.5000           0.0

In [25]:
cost.공사비.건축비.amt

21631.5

In [26]:
cost.공사비.건축비.vars

['index', 'name', '공사단가', '연면적', 'amt', '공정률표']

#### (4) 인입비 설정

In [27]:
with cost.공사비 as 공사비:    
    공사비.인입비 = 공사비.subacc('인입비')
    with 공사비.인입비 as c:
        c.적용비율 = 0.035#백만원
        c.연면적 = overview['area']['연면적']['평']
        c.amt = c.적용비율 * c.연면적
        c.addscd(idx.cstrn[0], c.amt)
        
    costsetting(공사비)

In [28]:
cost.공사비.smry

{'철거비': {'기존건물면적': 700, '철거단가': 0.3, 'amt': 210.0},
 '건축비': {'공사단가': 5.5,
  '연면적': 3933,
  'amt': 21631.5,
  '공정률표':               공정률       공정금액
  2023-04-30  0.011   237.9465
  2023-05-31  0.015   324.4725
  2023-06-30  0.018   389.3670
  2023-07-31  0.013   281.2095
  2023-08-31  0.016   346.1040
  2023-09-30  0.023   497.5245
  2023-10-31  0.030   648.9450
  2023-11-30  0.034   735.4710
  2023-12-31  0.031   670.5765
  2024-01-31  0.030   648.9450
  2024-02-29  0.030   648.9450
  2024-03-31  0.036   778.7340
  2024-04-30  0.045   973.4175
  2024-05-31  0.057  1232.9955
  2024-06-30  0.069  1492.5735
  2024-07-31  0.076  1643.9940
  2024-08-31  0.080  1730.5200
  2024-09-30  0.077  1665.6255
  2024-10-31  0.073  1579.0995
  2024-11-30  0.068  1470.9420
  2024-12-31  0.062  1341.1530
  2025-01-31  0.053  1146.4695
  2025-02-28  0.039   843.6285
  2025-03-31  0.014   302.8410},
 '인입비': {'적용비율': 0.035, '연면적': 3933, 'amt': 137.655}}

In [29]:
cost.공사비.amtlst

철거비      210.000
건축비    21631.500
인입비      137.655
dtype: float64

In [30]:
cost.공사비.amt

21979.155

### 4) 간접공사비 가정

In [31]:
cost.간접공사비 = cost.subacc('간접공사비')
with cost.간접공사비 as 간접공사비:
    간접공사비.설계비 = 간접공사비.subacc('설계비')
    with 간접공사비.설계비 as c:
        c.적용단가 = 0.10#백만원/평
        c.연면적 = overview['area']['연면적']['평']
        c.amt = c.적용단가 * c.연면적
        c.addscd(idx.cstrn[0], c.amt)
        
    간접공사비.감리비 = 간접공사비.subacc('감리비')
    with 간접공사비.감리비 as c:
        c.월단가 = 15.0#백만원/월
        c.amt = c.월단가 * len(idx.cstrn)
        c.addscd(idx.cstrn, [c.월단가] * len(idx.cstrn))
        
    간접공사비.인허가등 = 간접공사비.subacc('인허가등')
    with 간접공사비.인허가등 as c:
        c.amt = 300.0#백만원
        c.addscd(idx.loan[0], c.amt)
        
    costsetting(간접공사비)

In [32]:
cost.간접공사비.smry

{'설계비': {'적용단가': 0.1, '연면적': 3933, 'amt': 393.3},
 '감리비': {'월단가': 15.0, 'amt': 360.0},
 '인허가등': {'amt': 300.0}}

In [33]:
cost.간접공사비.amtlst

설계비     393.3
감리비     360.0
인허가등    300.0
dtype: float64

In [34]:
cost.간접공사비.amt

1053.3

### 5) 판매비 가정

In [35]:
cost.판매비 = cost.subacc('판매비')
with cost.판매비 as 판매비:
    판매비.MH운영비 = 판매비.subacc('MH운영비')
    with 판매비.MH운영비 as c:
        c.월단가 = 60#백만원/월
        c.amt = c.월단가 * len(idx.sales)
        c.addscd(idx.sales, [c.월단가] * len(idx.sales))
        
    판매비.광고비 = 판매비.subacc('광고비')
    with 판매비.광고비 as c:
        c.분양매출 = sales.분양매출['합계']
        c.적용비율 = 0.015
        c.amt = c.분양매출 * c.적용비율
        c.월단가 = c.amt / len(idx.sales)
        c.addscd(idx.sales, [c.월단가] * len(idx.sales))
        
    판매비.분양수수료 = 판매비.subacc('분양수수료')
    with 판매비.분양수수료 as c:
        c.수수료율_오피 = 0.05
        c.수수료율_근생 = 0.08
        c.분양가정테이블 = sales.분양률가정.copy() #deep copy
        c.분양가정테이블['수수료오피'] = c.분양가정테이블['계약오피'] * c.수수료율_오피
        c.분양가정테이블['수수료근생'] = c.분양가정테이블['계약근생'] * c.수수료율_근생
        c.수수료_오피 = c.분양가정테이블['수수료오피'].sum()
        c.수수료_근생 = c.분양가정테이블['수수료근생'].sum()
        c.amt = c.수수료_오피 + c.수수료_근생
        c.addscd(c.분양가정테이블.index, c.분양가정테이블['수수료오피'])
        c.addscd(c.분양가정테이블.index, c.분양가정테이블['수수료근생'])
    
    costsetting(판매비)

In [36]:
cost.판매비.분양수수료.dfall

            scd_in  scd_in_cum  scd_out  scd_out_cum  bal_strt  amt_in  amt_in_cum  amt_out  amt_out_cum  bal_end  rsdl_in_cum  rsdl_out_cum
2023-01-31     0.0         0.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0          0.0           0.0
2023-02-28     0.0         0.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0          0.0           0.0
2023-03-31     0.0         0.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0          0.0           0.0
2023-04-30   651.6       651.6      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0        651.6           0.0
2023-05-31     0.0       651.6      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0        651.6           0.0
2023-06-30     0.0       651.6      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0        651.6           0.0
2023-07-31     0.0       651.6      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0        651.6           0.0
2023-08-31     0.0       651.6      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0        651.6           0.0
2023-09-30     0.0       651.6      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0        651.6           0.0
2023-10-31   651.6      1303.2      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1303.2           0.0
2023-11-30     0.0      1303.2      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1303.2           0.0
2023-12-31     0.0      1303.2      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1303.2           0.0
2024-01-31     0.0      1303.2      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1303.2           0.0
2024-02-29     0.0      1303.2      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1303.2           0.0
2024-03-31     0.0      1303.2      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1303.2           0.0
2024-04-30   651.6      1954.8      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1954.8           0.0
2024-05-31     0.0      1954.8      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1954.8           0.0
2024-06-30     0.0      1954.8      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1954.8           0.0
2024-07-31     0.0      1954.8      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1954.8           0.0
2024-08-31     0.0      1954.8      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1954.8           0.0
2024-09-30     0.0      1954.8      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       1954.8           0.0
2024-10-31   651.6      2606.4      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       2606.4           0.0
2024-11-30     0.0      2606.4      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       2606.4           0.0
2024-12-31     0.0      2606.4      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       2606.4           0.0
2025-01-31     0.0      2606.4      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       2606.4           0.0
2025-02-28     0.0      2606.4      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       2606.4           0.0
2025-03-31     0.0      2606.4      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       2606.4           0.0
2025-04-30  1099.6      3706.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       3706.0           0.0
2025-05-31     0.0      3706.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       3706.0           0.0
2025-06-30     0.0      3706.0      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0       3706.0           0.0

In [37]:
cost.판매비.amt

6267.4

In [38]:
cost.판매비.amtlst

MH운영비    1500.0
광고비      1061.4
분양수수료    3706.0
dtype: float64

In [39]:
cost.판매비.smry

{'MH운영비': {'월단가': 60, 'amt': 1500},
 '광고비': {'분양매출': 70760.0,
  '적용비율': 0.015,
  'amt': 1061.3999999999999,
  '월단가': 42.455999999999996},
 '분양수수료': {'수수료율_오피': 0.05,
  '수수료율_근생': 0.08,
  '분양가정테이블':              오피   근생     계약오피    계약근생     계약소계  수수료오피  수수료근생
  2023-04-30  0.2  0.0  13032.0     0.0  13032.0  651.6    0.0
  2023-10-31  0.2  0.0  13032.0     0.0  13032.0  651.6    0.0
  2024-04-30  0.2  0.0  13032.0     0.0  13032.0  651.6    0.0
  2024-10-31  0.2  0.0  13032.0     0.0  13032.0  651.6    0.0
  2025-04-30  0.2  1.0  13032.0  5600.0  18632.0  651.6  448.0,
  '수수료_오피': 3258.0,
  '수수료_근생': 448.0,
  'amt': 3706.0}}

### 6) 일반사업비 가정

In [40]:
cost.일반사업비 = cost.subacc('일반사업비')
with cost.일반사업비 as 일반사업비:
    일반사업비.신탁수수료 = 일반사업비.subacc('신탁수수료')
    with 일반사업비.신탁수수료 as c:
        c.분양매출 = sales.분양매출['합계']
        c.적용비율 = 0.02
        c.amt = c.분양매출 * c.적용비율
        c.addscd(idx.loan[0], c.amt)
    
    일반사업비.시행사운영비 = 일반사업비.subacc('시행사운영비')
    with 일반사업비.시행사운영비 as c:
        c.월단가 = 30.0#백만원
        c.amt = c.월단가 * len(idx.sales)
        c.addscd(idx.sales, c.월단가)
        
    일반사업비.금융조달비 = 일반사업비.subacc('금융조달비')
    with 일반사업비.금융조달비 as c:
        c.감정평가 = 50.0#백만원
        c.사업성평가 = 40.0#백만원
        c.법무법인 = 40.0#백만원
        c.법무사 = 10.0#백만원
        c.amt = c.감정평가 + c.사업성평가 + c.법무법인 + c.법무사
        c.addscd(idx.loan[0], c.amt)
        
    일반사업비.예비비 = 일반사업비.subacc('예비비')
    with 일반사업비.예비비 as c:
        c.분양매출 = sales.분양매출['합계']
        c.적용비율 = 0.01
        c.amt = c.분양매출 * c.적용비율
        c.월단가 = c.amt / len(idx.loan)
        c.addscd(idx.loan, c.월단가)
        
    costsetting(일반사업비)

In [41]:
cost.일반사업비.smry

{'신탁수수료': {'분양매출': 70760.0, '적용비율': 0.02, 'amt': 1415.2},
 '시행사운영비': {'월단가': 30.0, 'amt': 750.0},
 '금융조달비': {'감정평가': 50.0,
  '사업성평가': 40.0,
  '법무법인': 40.0,
  '법무사': 10.0,
  'amt': 140.0},
 '예비비': {'분양매출': 70760.0,
  '적용비율': 0.01,
  'amt': 707.6,
  '월단가': 26.20740740740741}}

In [42]:
cost.일반사업비.amt

3012.7999999999997

In [43]:
cost.일반사업비.amtlst

신탁수수료     1415.2
시행사운영비     750.0
금융조달비      140.0
예비비        707.6
dtype: float64

### 7) 제세공과금 가정

In [44]:
cost.제세공과금 = cost.subacc('제세공과금')
with cost.제세공과금 as 제세공과금:
    제세공과금.상하수원인자부담금 = 제세공과금.subacc('상하수원인자부담금')
    with 제세공과금.상하수원인자부담금 as c:
        c.amt = 155.0#백만원
        c.addscd(idx.cstrn[0], c.amt)
    
    제세공과금.보존등기비 = 제세공과금.subacc('보존등기비')
    with 제세공과금.보존등기비 as c:
        c.과세표준 = cost.공사비.amt + cost.간접공사비.amt + cost.일반사업비.amt
        c.취득세 = c.과세표준 * 0.028      #2.80%
        c.지방교육세 = c.과세표준 * 0.0016  #0.16%
        c.농어촌특별세 = c.과세표준 * 0.0020 #0.20%
        c.amt = c.취득세 + c.지방교육세 + c.농어촌특별세
        c.addscd(idx.cstrn[-1], c.amt)

    costsetting(제세공과금)

In [45]:
cost.제세공과금.smry

{'상하수원인자부담금': {'amt': 155.0},
 '보존등기비': {'과세표준': 26045.254999999997,
  '취득세': 729.2671399999999,
  '지방교육세': 41.672408,
  '농어촌특별세': 52.090509999999995,
  'amt': 823.0300579999999}}

In [46]:
cost.제세공과금.amtlst

상하수원인자부담금    155.000000
보존등기비        823.030058
dtype: float64

In [47]:
cost.제세공과금.amt

978.0300579999999

## 2. Cost Account 함수 설정

### 1) 비용 추정 함수
* 매월 인출해야 할 한도대출금을 확정하기 위해서는 해당 월에 사용 예정된 사업비 금액을 추정해야 함.
* 사업비를 추정한 후 해당 금원만큼 한도대출금을 인출하고, 이후 인출된 금원으로 사업비를 지급함.

In [48]:
cost.mrg2.dfall

                  scd_in    scd_in_cum  scd_out  scd_out_cum  bal_strt  amt_in  amt_in_cum  amt_out  amt_out_cum  bal_end   rsdl_in_cum  rsdl_out_cum
2023-01-31      0.000000      0.000000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      0.000000           0.0
2023-02-28      0.000000      0.000000      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0      0.000000           0.0
2023-03-31  23516.407407  23516.407407      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  23516.407407           0.0
2023-04-30   1959.164907  25475.572315      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  25475.572315           0.0
2023-05-31    498.135907  25973.708222      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  25973.708222           0.0
2023-06-30    563.030407  26536.738630      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  26536.738630           0.0
2023-07-31    454.872907  26991.611537      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  26991.611537           0.0
2023-08-31    519.767407  27511.378944      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  27511.378944           0.0
2023-09-30    671.187907  28182.566852      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  28182.566852           0.0
2023-10-31   1474.208407  29656.775259      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  29656.775259           0.0
2023-11-30    909.134407  30565.909667      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  30565.909667           0.0
2023-12-31    844.239907  31410.149574      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  31410.149574           0.0
2024-01-31    822.608407  32232.757981      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  32232.757981           0.0
2024-02-29    822.608407  33055.366389      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  33055.366389           0.0
2024-03-31    952.397407  34007.763796      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  34007.763796           0.0
2024-04-30   1798.680907  35806.444704      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  35806.444704           0.0
2024-05-31   1406.658907  37213.103611      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  37213.103611           0.0
2024-06-30   1666.236907  38879.340519      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  38879.340519           0.0
2024-07-31   1817.657407  40696.997926      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  40696.997926           0.0
2024-08-31   1904.183407  42601.181333      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  42601.181333           0.0
2024-09-30   1839.288907  44440.470241      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  44440.470241           0.0
2024-10-31   2404.362907  46844.833148      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  46844.833148           0.0
2024-11-30   1644.605407  48489.438556      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  48489.438556           0.0
2024-12-31   1514.816407  50004.254963      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  50004.254963           0.0
2025-01-31   1320.132907  51324.387870      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  51324.387870           0.0
2025-02-28   1017.291907  52341.679778      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  52341.679778           0.0
2025-03-31   1299.534465  53641.214243      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  53641.214243           0.0
2025-04-30   1258.263407  54899.477651      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  54899.477651           0.0
2025-05-31     26.207407  54925.685058      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  54925.685058           0.0
2025-06-30      0.000000  54925.685058      0.0          0.0       0.0     0.0         0.0      0.0          0.0      0.0  54925.685058           0.0

In [49]:
@Setattr(cost)
def estimate_cost_amt(cost, idxno):
    cst = cost.mrg2
    return cst.scd_in[idxno]

In [50]:
cost.estimate_cost_amt(idx[2])

23516.40740740741

In [51]:
cost.estimate_cost_amt(idx.loan[0])

23516.40740740741

In [52]:
cost.estimate_cost_amt(idx.cstrn[0])

1959.1649074074073

### 2) 비용 지출 함수
* 운영계좌에서 개별 비용 Account에게 매월 지출 예정된 금원을 지출함.

In [53]:
@Setattr(cost)
def pay_cost_amt(cost, acc, idxno):
    amtttl = 0
    for key, item in cost.dct.items():
        for key2, item2 in item.dct.items():
            amt = item2.scd_in[idxno]
            acc.send(idxno, amt, item2, note=item2.name)
            amtttl += amt
    return amtttl

In [54]:
oprtg = Account(idx)
oprtg.addamt(idx[0], 10_000)

In [55]:
oprtg.df

            bal_strt   amt_in  amt_out  bal_end
2023-01-31       0.0  10000.0      0.0  10000.0
2023-02-28   10000.0      0.0      0.0  10000.0
2023-03-31   10000.0      0.0      0.0  10000.0
2023-04-30   10000.0      0.0      0.0  10000.0
2023-05-31   10000.0      0.0      0.0  10000.0
2023-06-30   10000.0      0.0      0.0  10000.0
2023-07-31   10000.0      0.0      0.0  10000.0
2023-08-31   10000.0      0.0      0.0  10000.0
2023-09-30   10000.0      0.0      0.0  10000.0
2023-10-31   10000.0      0.0      0.0  10000.0
2023-11-30   10000.0      0.0      0.0  10000.0
2023-12-31   10000.0      0.0      0.0  10000.0
2024-01-31   10000.0      0.0      0.0  10000.0
2024-02-29   10000.0      0.0      0.0  10000.0
2024-03-31   10000.0      0.0      0.0  10000.0
2024-04-30   10000.0      0.0      0.0  10000.0
2024-05-31   10000.0      0.0      0.0  10000.0
2024-06-30   10000.0      0.0      0.0  10000.0
2024-07-31   10000.0      0.0      0.0  10000.0
2024-08-31   10000.0      0.0      0.0  10000.0
2024-09-30   10000.0      0.0      0.0  10000.0
2024-10-31   10000.0      0.0      0.0  10000.0
2024-11-30   10000.0      0.0      0.0  10000.0
2024-12-31   10000.0      0.0      0.0  10000.0
2025-01-31   10000.0      0.0      0.0  10000.0
2025-02-28   10000.0      0.0      0.0  10000.0
2025-03-31   10000.0      0.0      0.0  10000.0
2025-04-30   10000.0      0.0      0.0  10000.0
2025-05-31   10000.0      0.0      0.0  10000.0
2025-06-30   10000.0      0.0      0.0  10000.0

In [56]:
cost.pay_cost_amt(oprtg, idx[2])

23516.40740740741

In [57]:
oprtg.df

                bal_strt   amt_in       amt_out       bal_end
2023-01-31      0.000000  10000.0      0.000000  10000.000000
2023-02-28  10000.000000      0.0      0.000000  10000.000000
2023-03-31  10000.000000      0.0  23516.407407 -13516.407407
2023-04-30 -13516.407407      0.0      0.000000 -13516.407407
2023-05-31 -13516.407407      0.0      0.000000 -13516.407407
2023-06-30 -13516.407407      0.0      0.000000 -13516.407407
2023-07-31 -13516.407407      0.0      0.000000 -13516.407407
2023-08-31 -13516.407407      0.0      0.000000 -13516.407407
2023-09-30 -13516.407407      0.0      0.000000 -13516.407407
2023-10-31 -13516.407407      0.0      0.000000 -13516.407407
2023-11-30 -13516.407407      0.0      0.000000 -13516.407407
2023-12-31 -13516.407407      0.0      0.000000 -13516.407407
2024-01-31 -13516.407407      0.0      0.000000 -13516.407407
2024-02-29 -13516.407407      0.0      0.000000 -13516.407407
2024-03-31 -13516.407407      0.0      0.000000 -13516.407407
2024-04-30 -13516.407407      0.0      0.000000 -13516.407407
2024-05-31 -13516.407407      0.0      0.000000 -13516.407407
2024-06-30 -13516.407407      0.0      0.000000 -13516.407407
2024-07-31 -13516.407407      0.0      0.000000 -13516.407407
2024-08-31 -13516.407407      0.0      0.000000 -13516.407407
2024-09-30 -13516.407407      0.0      0.000000 -13516.407407
2024-10-31 -13516.407407      0.0      0.000000 -13516.407407
2024-11-30 -13516.407407      0.0      0.000000 -13516.407407
2024-12-31 -13516.407407      0.0      0.000000 -13516.407407
2025-01-31 -13516.407407      0.0      0.000000 -13516.407407
2025-02-28 -13516.407407      0.0      0.000000 -13516.407407
2025-03-31 -13516.407407      0.0      0.000000 -13516.407407
2025-04-30 -13516.407407      0.0      0.000000 -13516.407407
2025-05-31 -13516.407407      0.0      0.000000 -13516.407407
2025-06-30 -13516.407407      0.0      0.000000 -13516.407407

In [58]:
cost.mrg2.dfall

                  scd_in    scd_in_cum  scd_out  scd_out_cum      bal_strt        amt_in    amt_in_cum  amt_out  amt_out_cum       bal_end   rsdl_in_cum  rsdl_out_cum
2023-01-31      0.000000      0.000000      0.0          0.0      0.000000      0.000000      0.000000      0.0          0.0      0.000000      0.000000           0.0
2023-02-28      0.000000      0.000000      0.0          0.0      0.000000      0.000000      0.000000      0.0          0.0      0.000000      0.000000           0.0
2023-03-31  23516.407407  23516.407407      0.0          0.0      0.000000  23516.407407  23516.407407      0.0          0.0  23516.407407      0.000000           0.0
2023-04-30   1959.164907  25475.572315      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   1959.164907           0.0
2023-05-31    498.135907  25973.708222      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   2457.300815           0.0
2023-06-30    563.030407  26536.738630      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   3020.331222           0.0
2023-07-31    454.872907  26991.611537      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   3475.204130           0.0
2023-08-31    519.767407  27511.378944      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   3994.971537           0.0
2023-09-30    671.187907  28182.566852      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   4666.159444           0.0
2023-10-31   1474.208407  29656.775259      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   6140.367852           0.0
2023-11-30    909.134407  30565.909667      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   7049.502259           0.0
2023-12-31    844.239907  31410.149574      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   7893.742167           0.0
2024-01-31    822.608407  32232.757981      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   8716.350574           0.0
2024-02-29    822.608407  33055.366389      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407   9538.958981           0.0
2024-03-31    952.397407  34007.763796      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  10491.356389           0.0
2024-04-30   1798.680907  35806.444704      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  12290.037296           0.0
2024-05-31   1406.658907  37213.103611      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  13696.696204           0.0
2024-06-30   1666.236907  38879.340519      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  15362.933111           0.0
2024-07-31   1817.657407  40696.997926      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  17180.590519           0.0
2024-08-31   1904.183407  42601.181333      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  19084.773926           0.0
2024-09-30   1839.288907  44440.470241      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  20924.062833           0.0
2024-10-31   2404.362907  46844.833148      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  23328.425741           0.0
2024-11-30   1644.605407  48489.438556      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  24973.031148           0.0
2024-12-31   1514.816407  50004.254963      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  26487.847556           0.0
2025-01-31   1320.132907  51324.387870      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  27807.980463           0.0
2025-02-28   1017.291907  52341.679778      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  28825.272370           0.0
2025-03-31   1299.534465  53641.214243      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  30124.806836           0.0
2025-04-30   1258.263407  54899.477651      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  31383.070243           0.0
2025-05-31     26.207407  54925.685058      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  31409.277651           0.0
2025-06-30      0.000000  54925.685058      0.0          0.0  23516.407407      0.000000  23516.407407      0.0          0.0  23516.407407  31409.277651           0.0

In [59]:
cost.토지비.토지매입가액.dfall

             scd_in  scd_in_cum  scd_out  scd_out_cum  bal_strt   amt_in  amt_in_cum  amt_out  amt_out_cum  bal_end  rsdl_in_cum  rsdl_out_cum
2023-01-31      0.0         0.0      0.0          0.0       0.0      0.0         0.0      0.0          0.0      0.0          0.0           0.0
2023-02-28      0.0         0.0      0.0          0.0       0.0      0.0         0.0      0.0          0.0      0.0          0.0           0.0
2023-03-31  20430.0     20430.0      0.0          0.0       0.0  20430.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-04-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-05-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-06-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-07-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-08-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-09-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-10-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-11-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2023-12-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-01-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-02-29      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-03-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-04-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-05-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-06-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-07-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-08-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-09-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-10-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-11-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2024-12-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2025-01-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2025-02-28      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2025-03-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2025-04-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2025-05-31      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0
2025-06-30      0.0     20430.0      0.0          0.0   20430.0      0.0     20430.0      0.0          0.0  20430.0          0.0           0.0